//constants
walkspd=0.2
frictGround=1.1
frictAir=1.1
frictSlide=1.01
slideTimeMax=30
grv=0.14
jumpPower=3
hspMax=6
vspMax=8
jumpsMax=1
doubleJumpWeakening=1.2
devMode=false
//variables
hsp=0
vsp=0
drawAng=0
onGround=false
jumps=jumpsMax
jumpAllowed=false
slideAllowed=false
slideTime=0
flipping=0
controlling=true
stepCooldown=0
stepCooldownMax=15
sliding=false
shootingNumber=0
cutscening=false
timeSlowEnabled=true
weaponHoming=0
bulletSpeedFact=1
hpMax=100
hp=hpMax
hitTime=0
slideDustDl=0
slideDustDlMax=1
hitFrames=0
invulnFrames=0
//inputs
r=0
l=0
u=0
d=0
rKey=[ord("D"),true] //key, usesKeyboard
lKey=[ord("A"),true]
uKey=[ord("W"),true]
dKey=[ord("S"),true]
//arms
arm1=instance_create_layer(x,y,"arms",arm_o)
arm1.shootkey=[mb_right,false] //key, usesKeyboard
arm1.drawXoff=-3
arm2=instance_create_layer(x,y,"arms",arm_o)
arm2.shootkey=[mb_left,false]
arm2.drawXoff=3

//initial spawn
image_xscale=-1
drawAng=-90
image_angle=90
controlling=false
groundControlReset=1//120
arm1.targAng=180
arm2.targAng=180